import { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: '',
    loadComponent: () =>
      import('./home/home.component').then((m) => m.HomeComponent),
    title: 'Odilbek Utamuratov - Senior Frontend Engineer',
  },
  {
    path: 'blog',
    loadComponent: () =>
      import('./blog/blog.component').then((m) => m.BlogComponent),
    title: 'Blog - Odilbek Utamuratov',
  },
  {
    path: 'problems',
    loadComponent: () => import('./problems/problems.component'),
  },
  {
    path: 'feed-telegram',
    loadComponent: () => import('./feed-telegram/feed-telegram'),
  },
  {
    path: 'angular-in-100-minutes',
    loadComponent: () => import('./course-page/course-page.component'),
    data: {
      cover: '../../../../assets/images/courses/samarali-kirish.jpg',
      title: 'Angularga samarali kirish | 100 soniyada',
      code: 'in100Minutes',
      topics: [
        'Angular nima? Nimaga Angular? Qanday Angular muhitini yaratamiz?',
        'Frontend vs Backend',
        'Angular sxemasi',
        "Biron narsani qanday samarali o'rganish mumkin?",
        'Komponenta nima?',
        'Input/Output',
        '@if va @for',
        'Injectable servicelar',
        'Property binding va Event binding. Interpolation',
        'HttpClient',
        'Routing',
        'Pipes',
        "Xatoliklarni o'qish",
        'VsCode uchun Angular extensionlari',
        'Roadmap',
      ],
      // videoLessons: [
      //   {
      //     link: 'https://youtu.be/VW7xfDoM3C8',
      //     title: 'Angularga samarali kirish | Trailer',
      //     duration: '1:56',
      //     cover: '../../../../assets/images/courses/samarali-kirish.jpg',
      //   },
      //   {
      //     link: 'https://youtu.be/pI-9RB78yaw',
      //     title: 'Nima uchun Angular?',
      //     duration: '4:34',
      //     cover: '../../../../assets/images/courses/nima-uchun-angular.png',
      //   },
      // ],
    },
  },
  {
    path: 'level-up',
    loadComponent: () => import('./course-page/course-page.component'),
    data: {
      cover: '../../../../assets/images/courses/levelUP.jpg',
      title: 'Level UP | Angular',
      code: 'levelUP',
      topics: [
        'Debounce Input',
        'Bundle size ni analiz qilish',
        'Masalani qanday yechish kerak',
        "Kirish. DI o'zi nima",
        "Injection token. Amaliyotda o'rni",
        "useValue, useFactory. Amaliyotda o'rni",
        "useClass, useExisting. Amaliyotda o'rni",
        'Refactoring. Dead code',
        'Refactoring. Lazy loading vs Pre loading',
        'Refactoring. Widget module va Yagona UI',
        'Refactoring. Third-party lib, UpToDate, Umumiy xulosalar',
        'Multiple projects',
        "Kutubxona va uni NPM'ga joylash",
      ],
      // videoLessons: [
      //   {
      //     link: 'https://youtu.be/CntDRS99seE',
      //     title: 'Level UP | Trailer',
      //     duration: '2:19',
      //     cover: '../../../../assets/images/courses/levelUP.jpg',
      //   },
      // ],
    },
  },
  {
    path: 'angular-tutorial',
    loadComponent: () => import('./course-page/course-page.component'),
    data: {
      cover: '../../../../assets/images/courses/angular-bg.jpg',
      title: 'Angular tutotial',
      code: 'unlimit',
      topics: [
        'Angularga kirish va asosiy tushunchalar',
        'Project tuzilmasi va asosiy fayllar tahlili',
        'Komponentlar: yaratilishi va ishlatilishi',
        'Template va data binding (interpolation, property binding, event binding)',
        'Two-way data binding',
        'Direktivalar: ngIf, ngFor, ngClass, ngStyle',
        "Komponentlar o‘rtasida ma'lumot almashinuvi",
        'Service va Dependency Injection',
        'HTTP so‘rovlar va REST API bilan ishlash',
        'RxJS va Observablesga kirish',
        'Router: sahifalar o‘rtasida navigatsiya',
        'Dinamik routing va parametrlar',
        'Formlar: Template-driven forms',
        'Formlar: Reactive forms',
        'Form validation (sintaktik va dasturlash asosida)',
        "Pipe'lar: Standart va Custom pipe yaratish",
        'Lifecycle Hooks tushunchasi',
        'Modul konsepsiyasi va Lazy Loading',
        'Angular Materialga kirish',
        'Reusable komponentlar yaratish',
        'State Management (ngRx asoslari)',
        'Error handling va not found sahifalar',
        'Auth: Login, JWT va AuthGuard',
        'Testlash: Unit Test va e2e Testlar',
        'Performance optimization (Change Detection, TrackBy)',
        'Deployment: Angular ilovasini build qilish va joylashtirish',
        'Yakuniy loyiha: Amaliy loyiha yaratish va takrorlash',
      ],
    },
  },
  {
    path: 'videos',
    loadComponent: () => import('./all-videos/all-videos'),
    title: 'Videolar - Odilbek Utamuratov',
  },
  {
    path: 'face-id',
    loadComponent: () => import('./face-id/face-id').then((c) => c.FaceId),
  },
];
