name: Docker Compose Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d

      - name: Show Docker Compose logs
        run: docker-compose logs
