name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ vars.WORK_DIR }}
            git pull origin main
            docker stop my-portfolio-web-1 || true
            docker rm my-portfolio-web-1 || true
            docker rmi my-portfolio-web || true
            docker compose up -d
